import "../globals.css";
import "react-toastify/dist/ReactToastify.css";
import { ToastContainer } from "react-toastify";
import Provider from "@/components/Provider";
export const metadata = {
	title: "Auth Blend",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className="bg-[#131324]">
				<Provider>
					{children}
					<ToastContainer />
				</Provider>
			</body>
		</html>
	);
}
